config/routes.rb
Purl::Application.routes.draw do
  resources :translations
  
  get ':old_url' => 'translations#translate', :as => 'translate_path'
  
  root :to => 'translations#index'

end

app/models/translation.rb
class Translation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  # GET /http://qld.gov.au/old
  def translate
    redirect_to Translation.find_by_old_url(params[:old_url]).new_url
  end
  
  # GET /translations
  # GET /translations.xml
  def index
    @translations = Translation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.xml
  def show
    @translation = Translation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @translation }
    end
  end

  # GET /translations/new
  # GET /translations/new.xml
  def new
    @translation = Translation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @translation }
    end
  end

  # GET /translations/1/edit
  def edit
    @translation = Translation.find(params[:id])
  end

  # POST /translations
  # POST /translations.xml
  def create
    @translation = Translation.new(params[:translation])

    respond_to do |format|
      if @translation.save
        format.html { redirect_to(@translation, :notice => 'Translation was successfully created.') }
        format.xml  { render :xml => @translation, :status => :created, :location => @translation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /translations/1
  # PUT /translations/1.xml
  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to(@translation, :notice => 'Translation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.xml
  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to(translations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Purl</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :old_url %><br />
    <%= f.text_field :old_url %>
  </div>
  <div class="field">
    <%= f.label :new_url %><br />
    <%= f.text_field :new_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Listing translations</h1>

<table>
  <tr>
    <th>Old url</th>
    <th>New url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @translations.each do |translation| %>
  <tr>
    <td><%= translation.old_url %></td>
    <td><%= translation.new_url %></td>
    <td><%= link_to 'Show', translation %></td>
    <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
    <td><%= link_to 'Destroy', translation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Translation', new_translation_path %>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Old url:</b>
  <%= @translation.old_url %>
</p>

<p>
  <b>New url:</b>
  <%= @translation.new_url %>
</p>


<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>